## Numpy array and basics
learn about numpy

In [2]:
import numpy as np

## Creating array from list

In [ ]:
arr_1d=np.array([1,2,3,4])
print("arr_1d: ", arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6]]) #2 array ko ek aur array me dalenge
print("arr_2d:", arr_2d)


arr_1d:  [1 2 3 4]
arr_2d: [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [5]:
py_list=[1,2,3,4]
print("Pynthon list multiplication",py_list*2)

np_array=np.array([1,2,3,4]) #eliment wise multiplication
print("Numpy array multiplication:", np_array*2)

import time
start=time.time()#for calculatiing in secounds
py_list=[i*2 for i in range(1000000)]
print("/n List operation time :",time.time()-start)

start=time.time()
np_array=np.arange(1000000)*2
print("/n Array operation time :",time.time()-start)




Pynthon list multiplication [1, 2, 3, 4, 1, 2, 3, 4]
Numpy array multiplication: [2 4 6 8]
/n List operation time : 0.09286355972290039
/n Array operation time : 0.009078264236450195


## creating arays from scratch



In [14]:
zeroes=np.zeros([3,4]) #rows , collums
print("zeroes of array :",zeroes)

ones=np.ones([3,4])
print("ones of array  :\n",ones)

full=np.full([3,4],7)
print("full of array  :\n",full)

random=np.random.random([3,4])
print("random of array  :\n",random)

sequence=np.arange(0,11,2)
print("sequence of array  :\n",sequence)



zeroes of array : [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones of array  :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full of array  :
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
random of array  :
 [[0.37845976 0.25893822 0.6063317  0.70369614]
 [0.18074571 0.55882394 0.85869143 0.86026369]
 [0.14294144 0.62228105 0.57627106 0.52991467]]
sequence of array  :
 [ 0  2  4  6  8 10]



## VECTOR,MATRIX AND TENSOR


In [16]:
vector=np.array([1,2,3])
print("Vector:\n",vector)

matrix=np.array([[1,2,3],
                 [4,5,4]])
print("Matrix:\n",matrix)


tensor=np.array([[[1,2],[3,4]],
                 [[3,4],[0,9]]])
print("Tenor:\n",tensor)


Vector:
 [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 4]]
Tenor:
 [[[1 2]
  [3 4]]

 [[3 4]
  [0 9]]]


## ARRAYS Property

In [20]:
arr=np.array([[1,2,3],
                [5,6,7]]) #at 7 or any other we can place other like float and bolean but due to numpy it work fast on its similar 
                             # kind of datas
print("Shape:\n",arr.shape)
print("Dimmension:\n",arr.ndim)
print("Size:\n",arr.size)
print("Dtype:\n",arr.dtype)


Shape:
 (2, 3)
Dimmension:
 2
Size:
 6
Dtype:
 int64


## Array Reshaping


In [ ]:
arr=np.arange(12)
print("Orignal array",arr)

reshaped=arr.reshape([3,4])
print("Reshaped array",reshaped)

#as in this case the flattered return the copy value as the orignal value is protected and made a copy and send 
flattered=reshaped.flatten()
print("Flattered array",flattered)

# it will return the view value(means the orignal one) not the copy value 
ravelled=reshaped.ravel()
print("Raveled array ",ravelled)

#Transpose  [a,b]        [a,d]
#           [d,e]        [b,e]   transpose baki from google
transpose=reshaped.T
print("Transpose array ",transpose)





Orignal array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattered array [ 0  1  2  3  4  5  6  7  8  9 10 11]
