In [2]:
import numpy as np
import matplotlib.pyplot as plt


In [8]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])
# : means "all".
# start:end means "from start index to end index (not including end)".
# You can use [row_slice, column_slice] to select parts of a 2D array.

print("=== ZOMATO SALES ===")
print("\n Salse Size:",sales_data.shape)
print("\nSample Data for 1st 3 rd restraunt",sales_data[:,1:])


=== ZOMATO SALES ===

 Salse Size: (5, 5)

Sample Data for 1st 3 rd restraunt [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]


## SALES DATA


In [15]:
print(np.sum(sales_data,axis=0))# axis = 0 for  the vertical addition
total_sales=np.sum(sales_data[:,1:],axis=0)
print(total_sales)

#for min sales amoung all
mim_sales=np.min(sales_data[:,1:],axis=1) # as axis  1 is for row vise
print(mim_sales)

#for max sales per year
max_sales=np.max(sales_data[:,1:],axis=0)
print(max_sales)

# AVG sales per restraunt
avg_salaes=np.mean(sales_data[:,1:],axis=1)
print(avg_salaes)


[     15  810000  945000 1085000 1240000]
[ 810000  945000 1085000 1240000]
[150000 120000 200000 180000 160000]
[200000 230000 260000 300000]
[200000. 152500. 247500. 225000. 195000.]


In [16]:
# For cumulative sales
cumsum=np.cumsum(sales_data[:,1:],axis=1)
print(cumsum)

[[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]


## Vector add and multiply

In [4]:
vector1=np.array([1,2,3,4,5])
vecto2=np.array([6,7,8,9,10])

print("Vector Addition",vector1+vecto2)

print("Vector Multiply",vector1*vecto2)

print("Dot product",np.dot(vector1,vecto2))

Vector Addition [ 7  9 11 13 15]
Vector Multiply [ 6 14 24 36 50]
Dot product 130


## Vectorized upper

In [6]:
restaurant_type=np.array(['biriyani','chinese','burger','pizza'])
vectorized_upper=np.vectorize(str.upper)
print("Vectorized Upper",vectorized_upper(restaurant_type))

Vectorized Upper ['BIRIYANI' 'CHINESE' 'BURGER' 'PIZZA']


## BRODCASTING means ek ek ke pas jakr will purform opperation

In [9]:
monthly_avg=sales_data[:,1:]/12 
print(monthly_avg)

[[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]
