## Array Slicing

In [2]:
import numpy as np

In [3]:
arr=np.array([1, 2, 3, 4, 5,6,7])  
print("Basic slicing",arr[2:7])
print("With Steps",arr[1:8:2])
print("Negative slicing",arr[-3])

Basic slicing [3 4 5 6 7]
With Steps [2 4 6]
Negative slicing 5


In [7]:
arr_2d=np.array([[1,2,3], # 0th row
                 [4,5,6],  #1st row
                 [7,8,9]])
print("Specific element :",arr_2d[2,1])
print("entire row",arr_2d[1])
print("entire columb",arr_2d[:,1])

Specific element : 8
entire row [4 5 6]
entire columb [2 5 8]


## SORTING

In [11]:
unsorted=np.array([1,2,3,1,2,4,5,9,8])
print("Sorting array",np.sort(unsorted))

arr_2d_unsorted=np.array([[3,1],[2,1],[4,1]])# mostly will use this 
print("sorting 2d array by colums",np.sort(arr_2d_unsorted,axis=0)) 

arr_2d_unsorted=np.array([[3,1],[2,1],[4,1]])# mostly will use this 
print("sorting 2d array by rows",np.sort(arr_2d_unsorted,axis=1)) 

Sorting array [1 1 2 2 3 4 5 8 9]
sorting 2d array by colums [[2 1]
 [3 1]
 [4 1]]
sorting 2d array by rows [[1 3]
 [1 2]
 [1 4]]


## Filtering

In [13]:
numbers=np.array([1,2,3,4,5,6,7,8,9])
even_number=numbers[numbers % 2==0]
print("Even numbers",even_number)

Even numbers [2 4 6 8]


## Filtering my mask

In [15]:
mask= numbers>5
print("Numbers greater than 5",numbers[mask])


Numbers greater than 5 [6 7 8 9]


## Fancy indices vs np.where()

In [17]:
indices=[0,2,4]
print(numbers[indices])

where_result=np.where(numbers>5)
print("NP where ",numbers[where_result])


[1 3 5]
NP where  [6 7 8 9]


In [19]:
condition_array=np.where(numbers>5,"true","false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true']


## Adding and Subtracting

In [21]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

combined=np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


## Array compatibility    

In [3]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])

print("Compatibility shapes",a.shape==b.shape)

Compatibility shapes True


## Entering new colum and row

In [ ]:
orignal=np.array([[1,2],[3,4]])
new_row=np.array([5,6])

with_new_row=np.vstack((orignal,new_row))
print("With new row:",with_new_row)

new_col=np.array([[8],[9]]) # indentation to be noted and precised
with_new_columb=np.hstack((orignal,new_col))
print("With new columb",with_new_columb)

With new row: [[1 2]
 [3 4]
 [5 6]]
With new columb [[1 2 8]
 [3 4 9]]


## Deleting array

In [8]:
arr=np.array([1,2,3,4,5])
deleeted=np.delete(arr,2)
print("deleted array:",deleeted)

deleted array: [1 2 4 5]
